<html>
    <head>
        <title>
            @yield('titulo')
        </title>
    </head>
    <body>
        <nav>
           @include('partials.nav')
        </nav>
        @yield('contenido')
    </body>
</html>