# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and deploy PHP app to Azure Web App - bibliotecaLaravel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_307B5084369C46238FC636EF4EAF777F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D62F15CF785F4F4ABA1924E315262F12 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_41F9ADE4BEFF45FFB9DE482A0F866880 }}

      #--Todo esto no es necesario al poner server.php
      #debug copia
      #- name: Verificar estructura de archivos
      #  run: ls -R
        
      #- name: Verificar existencia de index.php
      #  run: ls -l index.php || echo "No existe index.php"

      #Copia public en wwwroot
      #- name: Copy Laravel public folder content to root for App Service
      #  run: |
      #    mkdir -p public
      #    rm -rf ./public/storage || true
      #    cp -r public/* . ||true
      #    if [ -f public/.htaccess ]; then cp public/.htaccess .; fi
      #    if [ -f index.php ]; then sed -i "s|__DIR__ . \'/../|__DIR__ . \'/|g" index.php; fi
      #Fin copia public en wwwroot
      #--Fin de no es necesario al poner server.php
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'bibliotecaLaravel'
          slot-name: 'Production'
          package: .
          
      # Mover archivos luego del despliegue (opcional, si App Service lo permite)
      - name: 'Fix file placement via SSH'
        uses: azure/ssh@v1
        with:
         host: ${{ secrets.AZURE_WEBAPP_HOST }}
         username: ${{ secrets.AZURE_WEBAPP_USERNAME }}
         key: ${{ secrets.AZURE_WEBAPP_SSH_KEY }}
         script: |
            mv /home/site/wwwroot/nginx.conf /home/site/nginx.conf || true
            mv /home/site/wwwroot/startup.sh /home/site/startup.sh || true
            chmod +x /home/site/startup.sh || true
    
